
    /* 포지션 boolean 포함 */
    export const PLAYERS=
    [
      {
        "name": "Kareem Abdul-Jabbar",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 100,
        "def": 86,
        "id": 1
      },
      {
        "name": "Precious Achiuwa",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 51,
        "def": 66,
        "id": 2
      },
      {
        "name": "Michael Adams",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 88,
        "def": 72,
        "id": 3
      },
      {
        "name": "Steven Adams",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 73,
        "def": 65,
        "id": 4
      },
      {
        "name": "Bam Adebayo",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 86,
        "def": 85,
        "id": 5
      },
      {
        "name": "Ochai Agbaji",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 44,
        "def": 66,
        "id": 6
      },
      {
        "name": "Mark Aguirre",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 97,
        "def": 59,
        "id": 7
      },
      {
        "name": "Santi Aldama",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 41,
        "def": 57,
        "id": 8
      },
      {
        "name": "LaMarcus Aldridge",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 88,
        "def": 66,
        "id": 9
      },
      {
        "name": "Nickeil Alexander-Walker",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 67,
        "def": 51,
        "id": 10
      },
      {
        "name": "Grayson Allen",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 65,
        "def": 53,
        "id": 11
      },
      {
        "name": "Jarrett Allen",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 75,
        "def": 77,
        "id": 12
      },
      {
        "name": "Ray Allen",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 92,
        "def": 77,
        "id": 13
      },
      {
        "name": "Jose Alvarado",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 66,
        "def": 76,
        "id": 14
      },
      {
        "name": "Justin Anderson",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": true,
        "atk": 44,
        "def": 48,
        "id": 15
      },
      {
        "name": "Kyle Anderson",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 66,
        "def": 55,
        "id": 16
      },
      {
        "name": "Giannis Antetokounmpo",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": true,
        "atk": 93,
        "def": 84,
        "id": 17
      },
      {
        "name": "Thanasis Antetokounmpo",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 40,
        "def": 56,
        "id": 18
      },
      {
        "name": "Carmelo Anthony",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 97,
        "def": 69,
        "id": 19
      },
      {
        "name": "Cole Anthony",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 70,
        "def": 39,
        "id": 20
      },
      {
        "name": "OG Anunoby",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 77,
        "def": 83,
        "id": 21
      },
      {
        "name": "Ryan Arcidiacono",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 47,
        "def": 53,
        "id": 22
      },
      {
        "name": "Gilbert Arenas",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 89,
        "def": 51,
        "id": 23
      },
      {
        "name": "Trevor Ariza",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 71,
        "def": 73,
        "id": 24
      },
      {
        "name": "Omer Asik",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 70,
        "def": 75,
        "id": 25
      },
      {
        "name": "D.J. Augustin",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 42,
        "def": 23,
        "id": 26
      },
      {
        "name": "Deni Avdija",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 64,
        "def": 76,
        "id": 27
      },
      {
        "name": "Joel Ayayi",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 48,
        "def": 55,
        "id": 28
      },
      {
        "name": "Deandre Ayton",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 86,
        "def": 75,
        "id": 29
      },
      {
        "name": "Udoka Azubuike",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 44,
        "def": 62,
        "id": 30
      },
      {
        "name": "Marvin Bagley III",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 64,
        "def": 58,
        "id": 31
      },
      {
        "name": "Vin Baker",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": true,
        "atk": 87,
        "def": 55,
        "id": 32
      },
      {
        "name": "Patrick Baldwin Jr.",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 42,
        "def": 53,
        "id": 33
      },
      {
        "name": "LaMelo Ball",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 90,
        "def": 41,
        "id": 34
      },
      {
        "name": "Lonzo Ball",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 77,
        "def": 82,
        "id": 35
      },
      {
        "name": "Mo Bamba",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 70,
        "def": 66,
        "id": 36
      },
      {
        "name": "Paolo Banchero",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 87,
        "def": 73,
        "id": 37
      },
      {
        "name": "Desmond Bane",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 82,
        "def": 73,
        "id": 38
      },
      {
        "name": "Dalano Banton",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 37,
        "def": 44,
        "id": 39
      },
      {
        "name": "Cat Barber",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 48,
        "def": 53,
        "id": 40
      },
      {
        "name": "Charles Barkley",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 99,
        "def": 67,
        "id": 41
      },
      {
        "name": "Harrison Barnes",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 82,
        "def": 54,
        "id": 42
      },
      {
        "name": "Scottie Barnes",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 73,
        "def": 67,
        "id": 43
      },
      {
        "name": "Dana Barros",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 83,
        "def": 46,
        "id": 44
      },
      {
        "name": "R.J. Barrett",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 84,
        "def": 54,
        "id": 45
      },
      {
        "name": "Will Barton",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 75,
        "def": 45,
        "id": 46
      },
      {
        "name": "Charles Bassey",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 44,
        "def": 58,
        "id": 47
      },
      {
        "name": "Paris Bass",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 44,
        "def": 54,
        "id": 48
      },
      {
        "name": "Keita Bates-Diop",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 43,
        "def": 48,
        "id": 49
      },
      {
        "name": "Nicolas Batum",
        "pos": "SG",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 84,
        "def": 76,
        "id": 50
      },
      {
        "name": "Kent Bazemore",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 64,
        "def": 58,
        "id": 51
      },
      {
        "name": "Darius Bazley",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 55,
        "def": 41,
        "id": 52
      },
      {
        "name": "Bradley Beal",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 93,
        "def": 77,
        "id": 53
      },
      {
        "name": "Malik Beasley",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 65,
        "def": 45,
        "id": 54
      },
      {
        "name": "MarJon Beauchamp",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 40,
        "def": 45,
        "id": 55
      },
      {
        "name": "Jordan Bell",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 46,
        "def": 56,
        "id": 56
      },
      {
        "name": "Raja Bell",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 73,
        "def": 79,
        "id": 57
      },
      {
        "name": "DeAndre Bembry",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 41,
        "def": 65,
        "id": 58
      },
      {
        "name": "Davis Bertans",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 70,
        "def": 41,
        "id": 59
      },
      {
        "name": "Patrick Beverley",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 72,
        "def": 81,
        "id": 60
      },
      {
        "name": "Saddiq Bey",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 67,
        "def": 56,
        "id": 61
      },
      {
        "name": "Mike Bibby",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 86,
        "def": 64,
        "id": 62
      },
      {
        "name": "Chauncey Billups",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 84,
        "def": 82,
        "id": 63
      },
      {
        "name": "Khem Birch",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 40,
        "def": 46,
        "id": 64
      },
      {
        "name": "Larry Bird",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 95,
        "def": 74,
        "id": 65
      },
      {
        "name": "Goga Bitadze",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 46,
        "def": 46,
        "id": 66
      },
      {
        "name": "Bismack Biyombo",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 44,
        "def": 56,
        "id": 67
      },
      {
        "name": "Nemanja Bjelica",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 70,
        "def": 55,
        "id": 68
      },
      {
        "name": "Rolando Blackman",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 86,
        "def": 70,
        "id": 69
      },
      {
        "name": "Eric Bledsoe",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 83,
        "def": 70,
        "id": 70
      },
      {
        "name": "Keljin Blevins",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 40,
        "def": 52,
        "id": 71
      },
      {
        "name": "Bojan Bogdanovic",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 82,
        "def": 45,
        "id": 72
      },
      {
        "name": "Bogdan Bogdanovic",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 75,
        "def": 45,
        "id": 73
      },
      {
        "name": "Andrew Bogut",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 77,
        "def": 77,
        "id": 74
      },
      {
        "name": "Bol Bol",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 68,
        "def": 41,
        "id": 75
      },
      {
        "name": "Leandro Bolmaro",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 40,
        "def": 53,
        "id": 76
      },
      {
        "name": "Isaac Bonga",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 65,
        "def": 55,
        "id": 77
      },
      {
        "name": "Devin Booker",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 96,
        "def": 77,
        "id": 78
      },
      {
        "name": "Carlos Boozer",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 84,
        "def": 68,
        "id": 79
      },
      {
        "name": "Chris Bosh",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 88,
        "def": 72,
        "id": 80
      },
      {
        "name": "Brandon Boston Jr.",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 45,
        "def": 42,
        "id": 81
      },
      {
        "name": "Chris Boucher",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 70,
        "def": 62,
        "id": 82
      },
      {
        "name": "James Bouknight",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 45,
        "def": 44,
        "id": 83
      },
      {
        "name": "Avery Bradley",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 75,
        "def": 79,
        "id": 84
      },
      {
        "name": "Tony Bradley",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 55,
        "def": 72,
        "id": 85
      },
      {
        "name": "Elton Brand",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 86,
        "def": 66,
        "id": 86
      },
      {
        "name": "Malaki Branham",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 44,
        "def": 52,
        "id": 87
      },
      {
        "name": "Terrell Brandon",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 80,
        "def": 72,
        "id": 88
      },
      {
        "name": "Christian Braun",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 46,
        "def": 54,
        "id": 89
      },
      {
        "name": "Ignas Brazdeikis",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 42,
        "def": 53,
        "id": 90
      },
      {
        "name": "Corey Brewer",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 73,
        "def": 78,
        "id": 91
      },
      {
        "name": "Mikal Bridges",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 81,
        "def": 81,
        "id": 92
      },
      {
        "name": "Oshae Brissett",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 51,
        "def": 21,
        "id": 93
      },
      {
        "name": "Malcolm Brogdon",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 79,
        "def": 73,
        "id": 94
      },
      {
        "name": "Armoni Brooks",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 42,
        "def": 47,
        "id": 95
      },
      {
        "name": "Dillon Brooks",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 72,
        "def": 81,
        "id": 96
      },
      {
        "name": "Bruce Brown",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 73,
        "def": 76,
        "id": 97
      },
      {
        "name": "Charles Brown Jr.",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 44,
        "def": 59,
        "id": 98
      },
      {
        "name": "Chaundee Brown",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 48,
        "def": 56,
        "id": 99
      },
      {
        "name": "Greg Brown III",
        "pos": "SF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": false,
        "atk": 41,
        "def": 41,
        "id": 100
      },
      {
        "name": "Jaylen Brown",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 90,
        "def": 78,
        "id": 101
      },
      {
        "name": "Moses Brown",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 66,
        "def": 57,
        "id": 102
      },
      {
        "name": "Sterling Brown",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 38,
        "def": 49,
        "id": 103
      },
      {
        "name": "Troy Brown Jr.",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 60,
        "def": 33,
        "id": 104
      },
      {
        "name": "Jalen Brunson",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 92,
        "def": 63,
        "id": 105
      },
      {
        "name": "Kobe Bryant",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 100,
        "def": 79,
        "id": 106
      },
      {
        "name": "Thomas Bryant",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 47,
        "def": 56,
        "id": 107
      },
      {
        "name": "Shaq Buchanan",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 48,
        "def": 55,
        "id": 108
      },
      {
        "name": "Reggie Bullock",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 64,
        "def": 45,
        "id": 109
      },
      {
        "name": "Alec Burks",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 57,
        "def": 57,
        "id": 110
      },
      {
        "name": "Trey Burke",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 44,
        "def": 52,
        "id": 111
      },
      {
        "name": "Jared Butler",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 43,
        "def": 58,
        "id": 112
      },
      {
        "name": "Jimmy Butler",
        "pos": "SF",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 92,
        "def": 82,
        "id": 113
      },
      {
        "name": "Devontae Cacok",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": false,
        "atk": 41,
        "def": 53,
        "id": 114
      },
      {
        "name": "Kentavious Caldwell-Pope",
        "pos": "SG",
        "pg": false,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 72,
        "def": 79,
        "id": 115
      },
      {
        "name": "Marcus Camby",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 64,
        "def": 82,
        "id": 116
      },
      {
        "name": "Facundo Campazzo",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 41,
        "def": 59,
        "id": 117
      },
      {
        "name": "Vlatko Cancar",
        "pos": "PF",
        "pg": false,
        "sg": false,
        "sf": true,
        "pf": true,
        "c": true,
        "atk": 42,
        "def": 54,
        "id": 118
      },
      {
        "name": "Devin Cannady",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 50,
        "def": 47,
        "id": 119
      },
      {
        "name": "Clint Capela",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": true,
        "atk": 70,
        "def": 79,
        "id": 120
      },
      {
        "name": "Vernon Carey Jr.",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 46,
        "def": 55,
        "id": 121
      },
      {
        "name": "Jevon Carter",
        "pos": "PG",
        "pg": true,
        "sg": false,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 39,
        "def": 47,
        "id": 122
      },
      {
        "name": "Vince Carter",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": false,
        "c": false,
        "atk": 93,
        "def": 75,
        "id": 123
      },
      {
        "name": "Wendell Carter Jr.",
        "pos": "C",
        "pg": false,
        "sg": false,
        "sf": false,
        "pf": true,
        "c": true,
        "atk": 65,
        "def": 77,
        "id": 124
      },
      {
        "name": "Alex Caruso",
        "pos": "SG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 65,
        "def": 80,
        "id": 125
      },
      {
        "name": "Sam Cassell",
        "pos": "PG",
        "pg": true,
        "sg": true,
        "sf": false,
        "pf": false,
        "c": false,
        "atk": 81,
        "def": 55,
        "id": 126
      },
      {
        "name": "Brad Jones",
        "pos": "SF",
        "pg": true,
        "sg": true,
        "sf": true,
        "pf": true,
        "c": false,
        "atk": 30,
        "def": 30,
        "id": 127
      }
    ]

    ;
