    export const TEAMS=[
                         { "name": "보스턴",      "owner": "흑곰" },
                         { "name": "덴버",        "owner": "크블덕후" },
                         { "name": "포틀랜드",    "owner": "돈대창" },
                         { "name": "미네소타",    "owner": "Arrows" },
                         { "name": "휴스턴",      "owner": "거북이와" },
                         { "name": "클리블랜드",  "owner": "데드캣" },
                         { "name": "밀워키",      "owner": "이승엽" },
                         { "name": "골든스테이트","owner": "스티브유" },
                         { "name": "필라델피아",  "owner": "NEWYORK" },
                         { "name": "디트로이트",  "owner": "SPACEX" },
                         { "name": "인디애나",    "owner": "OC10" },
                         { "name": "샌안토니오",  "owner": "LISA" },
                         { "name": "뉴올리언스",  "owner": "SCREAM" },
                         { "name": "멤피스",      "owner": "DAY1" },
                         { "name": "워싱턴",      "owner": "짤짤이서폿GOAT" },
                         { "name": "피닉스",      "owner": "악성커퀴벌레" },
                         { "name": "레이커스",    "owner": "크림치즈" },
                         { "name": "오클라호마",  "owner": "NEWSTARAIN" },
                         { "name": "새크라멘토",  "owner": "범고래" },
                         { "name": "클리퍼스",    "owner": "갓토끼" },
                         { "name": "뉴욕",        "owner": "DPRKOREA" },
                         { "name": "댈러스",      "owner": "BALLON" },
                         { "name": "마이애미",    "owner": "Where" },
                         { "name": "샬럿",        "owner": "SNIPERAND" },
                         { "name": "아틀란타",    "owner": "제일런윌리엄슨" },
                         { "name": "시카고",      "owner": "도장" },
                         { "name": "유타",        "owner": "HIDEONBUSH" },
                         { "name": "토론토",      "owner": "총말론" },
                         { "name": "올랜도",      "owner": "훔바바" },
                         { "name": "브루클린",    "owner": "CASINO" }
                       ];
